# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-03 05:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=200)),
                ('application_version', models.CharField(max_length=200, null=True)),
                ('package_name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('telephony_identifiers_leakage', models.TextField(null=True)),
                ('device_settings_harvesting', models.TextField(null=True)),
                ('location_lookup', models.TextField(null=True)),
                ('connection_interfaces_exfiltration', models.TextField(null=True)),
                ('telephony_services_abuse', models.TextField(null=True)),
                ('audio_video_eavesdropping', models.TextField(null=True)),
                ('suspicious_connection_establishment', models.TextField(null=True)),
                ('pim_data_leakage', models.TextField(null=True)),
                ('code_execution', models.TextField(null=True)),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('file_list', models.TextField(null=True)),
                ('certificate_information', models.TextField(null=True)),
                ('md5', models.CharField(max_length=32, null=True)),
                ('sha1', models.CharField(max_length=40, null=True)),
                ('sha256', models.CharField(max_length=64, null=True)),
                ('main_activity', models.TextField(null=True)),
                ('activities', models.TextField(null=True)),
                ('permissions', models.TextField(null=True)),
                ('features', models.TextField(null=True)),
                ('classes_list', models.TextField(null=True)),
                ('internal_classes_list', models.TextField(null=True)),
                ('external_classes_list', models.TextField(null=True)),
                ('internal_packages_list', models.TextField(null=True)),
                ('external_packages_list', models.TextField(null=True)),
                ('intents_sent', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('virustotal_report_link', models.TextField(null=True)),
                ('json_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
    ]
