# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-05 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDecisionTreeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'My Decision Tree Model',
                'verbose_name_plural': 'My Decision Tree Models',
            },
        ),
    ]
